name: schedule_tg

services:
  bot:
    build: ..
    volumes:
      - ../configs:/app/configs
      - ../src:/app/src
      - ${SSL_CERT:-../configs}:/ssl_keys:ro
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBHOOK_HOST: ${WEBHOOK_HOST}
      WEBAPP_HOST: ${WEBAPP_HOST:-0.0.0.0}
      WEBAPP_PORT: ${WEBAPP_PORT:-8080}
      SSL_CERT: ${SSL_CERT:-../configs}
      CERT_NAME: ${CERT_NAME:-}
      SCHEDULE_PATH: ${SCHEDULE_PATH}
      FIRST_WEEK_NUMBER: ${FIRST_WEEK_NUMBER}
      TZ: ${TIMEZONE}
      ADMINS: ${ADMINS}
      DEBUG: False
    ports:
      - ${LOCAL_MACHINE_URL:-8080}:${WEBAPP_PORT:-8080}
